version: 2.1

commands:
  print_pipeline_id:
    parameters:
      id_me:
        type: string
        default: "provide your ID"

    steps:
      - run: echo << parameters.id_me >>



jobs:
  print_id:
    docker:
      - image: circleci/node:13.8.0  
    steps:
      - print_pipeline_id:           # invoke command "print-pipeline_id"
          id_me: ${CIRCLE_WORKFLOW_ID}
          

workflows:
  my_workflow:
    jobs:
      - print_id
      
